### ISSUE TITLE
header search paths or something

### ISSUE THREAD

**Issue by sbwoodside** [heisters/iOS-oscpack#1]
I'm including this in my Xcode project and I'm getting this kind of error:

/Users/simon/sandbox/monolith/circles/Files/Lib/iOS-oscpack/Vendor/oscpack_1_1_0/ip/posix/UdpSocket.cpp:61:10: 'ip/TimerListener.h' file not found

I've tried adding this to my Header Search Paths

$(SRCROOT)/Files/Lib/iOS-oscpack/Vendor/oscpack_1_1_0

But still no luck. How do I make this work?

**Comment by heisters** [comment]
Hm, not sure. The way I've included it before is to add the `iOS-oscpack.xcodeproj` as a subproject of the  XCode workspace. That way, the subproject takes care of all the settings. You'll need to edit the subproject's build settings and change OSCPACK_DIR to the directory of the xcodeproj. I suppose I could just change that to SRCROOT or something...

Let me know how it goes.

**Comment by sbwoodside** [comment]
OK I’ll try that out.
